# Generated by cucumber-sinatra. (2011-05-01 13:40:51 +0200)

ENV['RACK_ENV'] = 'test'

APP_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..', '..'))

require File.join(File.dirname(__FILE__), '..', '..', 'lib/poole.rb')

# Set albums dir here
Poole::Album.albums_dir = "/home/bjorne/sandbox" # File.expand_path(File.join(File.dirname(__FILE__), '../../sandbox'))

require File.join(File.dirname(__FILE__), '..', '..', 'spec/factories/album_factory.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Poole::App

class AppWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  AppWorld.new
end
